package io.github.jfelixy.concurrentlabs.exceptions;

public class RecursoNotFound extends RuntimeException {
    public RecursoNotFound(String message) {
        super(message);
    }
}
